version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/expressdb
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: express-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expressdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
